GET http://localhost:8080/admin/dashboard

###
GET http://localhost:8080/admin/dashboard/addNewProduct

###
GET http://localhost:8080/api/product/category

###
GET http://localhost:8080/api/product/search?
    page=0&
    search=P&
    getFeatures=true

###
GET http://localhost:8080/api/product/2

###
GET http://localhost:8080/api/product/search?q=Product&page=0&feature=true&sort=PRICE_DESC&filters=RAM:16GB

###
GET http://localhost:8080/api/user/order/history?page=0
